language: ruby
rvm:
- ruby-head
- 2.5.0
- 2.4.3
- 2.3.5
before_install:
    - gem update --system
    - gem install bundler
script: bundle exec rake ci
#sudo: false
#cache: bundler
addons:
  code_climate:
    repo_token: c30552ebdf8e631457b7dc321138e8d1455e36def696c453ba9428dc082f247f
matrix:
  allow_failures:
  - rvm: ruby-head
