# frozen_string_literal: true

require "json"

module Plotly
  # The attribute tree of the bundled plotly.js release, generated by `rake schema:generate`.
  class Schema
    PATH = File.expand_path("schema/plot-schema.json", __dir__)
    SUBPLOT_SUFFIX = /\A(?<base>[a-z]+?)(?<n>[2-9]|[1-9]\d+)\z/

    # One attribute: an object with children, an array of objects, or a leaf value.
    class Node
      attr_reader :name

      def initialize(name, spec)
        @name = name
        @spec = spec
      end

      def object? = @spec.key?("attrs")

      def array? = @spec.key?("array")

      def leaf? = @spec.key?("type")

      def subplot? = @spec["subplot"] == true

      def attribute_names = @spec.fetch("attrs", {}).keys

      # @return [Node, nil] the child attribute, or nil when plotly.js does not define it
      def child(key)
        attrs = @spec["attrs"] or return nil
        key = key.to_s
        return Node.new(key, attrs[key]) if attrs.key?(key)

        match = SUBPLOT_SUFFIX.match(key) or return nil
        base = attrs[match[:base]]
        Node.new(key, base) if base&.fetch("subplot", false)
      end

      # @return [Node] the schema of each element of an array of objects
      def item = Node.new(name.sub(/s\z/, ""), @spec.fetch("array"))

      def type = @spec["type"]

      def values = @spec.fetch("values", [])

      def flags = @spec.fetch("flags", [])

      def extras = @spec.fetch("extras", [])

      def array_ok? = @spec["array_ok"] == true

      def min = @spec["min"]

      def max = @spec["max"]
    end

    def self.default
      @default ||= new(JSON.parse(File.read(PATH)))
    end

    def initialize(raw)
      @raw = raw
    end

    def plotly_js_version = @raw.fetch("plotly_js")

    def trace_types = @raw.fetch("traces").keys

    # @return [Node, nil]
    def trace(type)
      spec = @raw.fetch("traces")[type.to_s]
      Node.new(type.to_s, spec) if spec
    end

    def layout = Node.new("layout", @raw.fetch("layout"))

    def config = Node.new("config", @raw.fetch("config"))
  end
end
