# frozen_string_literal: true

require "json"

module Plotly
  # The attribute tree of the bundled plotly.js release, generated by `rake schema:generate`.
  class Schema
    # The generated schema file.
    PATH = File.expand_path("schema/plot-schema.json", __dir__)
    # Numbered subplot ids: xaxis2, scene3 (plotly.js has no xaxis1).
    SUBPLOT_SUFFIX = /\A(?<base>[a-z]+?)(?<n>[2-9]|[1-9]\d+)\z/

    # One attribute: an object with children, an array of objects, or a leaf value.
    class Node
      attr_reader :name

      def initialize(name, spec)
        @name = name
        @spec = spec
      end

      def object? = @spec.key?("attrs")

      def array? = @spec.key?("array")

      def leaf? = @spec.key?("type")

      def subplot? = @spec["subplot"] == true

      # @return [Array<String>] names of the children of an object
      def attribute_names = @spec.fetch("attrs", {}).keys

      # @return [Node, nil] the child attribute, or nil when plotly.js does not define it
      def child(key)
        attrs = @spec["attrs"] or return nil
        key = key.to_s
        return Node.new(key, attrs[key]) if attrs.key?(key)

        match = SUBPLOT_SUFFIX.match(key) or return nil
        base = attrs[match[:base]]
        Node.new(key, base) if base&.fetch("subplot", false)
      end

      # @return [Node] the schema of each element of an array of objects
      def item = Node.new(name.sub(/s\z/, ""), @spec.fetch("array"))

      # @return [String, nil] plotly.js value type of a leaf: "number", "enumerated", "color", ...
      def type = @spec["type"]

      # @return [Array] allowed values of an enumerated leaf; "/.../" strings are patterns
      def values = @spec.fetch("values", [])

      # @return [Array<String>] flags of a flaglist leaf, joined with "+"
      def flags = @spec.fetch("flags", [])

      # @return [Array<String>] flaglist values that stand alone, such as "none"
      def extras = @spec.fetch("extras", [])

      # Whether the leaf also accepts an array of values, one per point.
      def array_ok? = @spec["array_ok"] == true

      # @return [Numeric, nil] lower bound of a number leaf
      def min = @spec["min"]

      # @return [Numeric, nil] upper bound of a number leaf
      def max = @spec["max"]
    end

    # @return [Schema] the schema of the bundled plotly.js release, loaded once
    def self.default
      @default ||= new(JSON.parse(File.read(PATH)))
    end

    def initialize(raw)
      @raw = raw
    end

    # @return [String] the plotly.js release the schema was generated from
    def plotly_js_version = @raw.fetch("plotly_js")

    # @return [Array<String>] every trace type: "bar", "scatter", ...
    def trace_types = @raw.fetch("traces").keys

    # @return [Node, nil]
    def trace(type)
      spec = @raw.fetch("traces")[type.to_s]
      Node.new(type.to_s, spec) if spec
    end

    # @return [Node] layout attributes, including those trace types add (barmode, ...)
    def layout = Node.new("layout", @raw.fetch("layout"))

    # @return [Node] plotly.js config options
    def config = Node.new("config", @raw.fetch("config"))
  end
end
